//! Generated by `just gen-claims` from `xtask/kips.toml`; do not edit.
//!
//! Every `symbol:` evidence in the KIP registry, named so the compiler
//! resolves it. A KIP that cites an item the crate does not have fails
//! `cargo check --all-targets` here.
// `{ .. }` names a variant whatever its shape, so a unit variant gets one too.
#![allow(dead_code, unused_imports, clippy::unneeded_struct_pattern)]

#[rustfmt::skip]
fn evidence() {
    // KIP-255
    { use krafka::auth::OAuthBearerToken as _; }
    // KIP-255
    let _ = krafka::auth::AuthConfig::sasl_oauthbearer_token;
    // KIP-320
    { use krafka::consumer::OffsetAndMetadata as _; }
    // KIP-320
    { use krafka::admin::EpochEndOffset as _; }
    // KIP-360
    { use krafka::producer::TransactionalProducer as _; }
    // KIP-368
    { use krafka::auth::AuthConfig as _; }
    // KIP-373
    let _ = krafka::admin::CreateDelegationTokenOptions::owner;
    // KIP-373
    { use krafka::admin::DelegationToken as _; }
    // KIP-405
    let _ = |v: krafka::admin::OffsetSpec| matches!(v, krafka::admin::OffsetSpec::EarliestLocal { .. });
    // KIP-429
    let _ = |v: krafka::consumer::PartitionAssignmentStrategy| matches!(v, krafka::consumer::PartitionAssignmentStrategy::CooperativeSticky { .. });
    // KIP-429
    { use krafka::consumer::ConsumerRebalanceListener as _; }
    // KIP-447
    let _ = krafka::producer::TransactionalProducer::send_offsets;
    // KIP-447
    { use krafka::consumer::ConsumerGroupMetadata as _; }
    // KIP-455
    { use krafka::admin::AlterPartitionReassignmentsOptions as _; }
    // KIP-455
    { use krafka::admin::PartitionReassignment as _; }
    // KIP-460
    { use krafka::admin::ElectionType as _; }
    // KIP-464
    { use krafka::admin::NewTopic as _; }
    // KIP-512
    { use krafka::interceptor::ProducerInterceptor as _; }
    // KIP-518
    let _ = krafka::admin::ListConsumerGroupsOptions::states;
    // KIP-554
    { use krafka::admin::ScramCredentialInfo as _; }
    // KIP-554
    { use krafka::admin::ScramCredentialUpsertion as _; }
    // KIP-584
    { use krafka::admin::FeatureMetadata as _; }
    // KIP-584
    { use krafka::admin::UpdateFeaturesOptions as _; }
    // KIP-664
    { use krafka::admin::ProducerState as _; }
    // KIP-664
    { use krafka::admin::TransactionDescription as _; }
    // KIP-664
    { use krafka::admin::TransactionListing as _; }
    // KIP-664
    { use krafka::admin::AbortTransactionOptions as _; }
    // KIP-679
    let _ = krafka::producer::ProducerBuilder::idempotent;
    // KIP-714
    let _ = krafka::producer::ProducerBuilder::metrics_push;
    // KIP-714
    let _ = krafka::consumer::Consumer::client_instance_id;
    // KIP-734
    let _ = |v: krafka::admin::OffsetSpec| matches!(v, krafka::admin::OffsetSpec::MaxTimestamp { .. });
    // KIP-768
    #[cfg(feature = "oauth-oidc")]
    { use krafka::auth::OidcTokenProvider as _; }
    // KIP-768
    #[cfg(feature = "oauth-oidc")]
    let _ = |v: krafka::auth::ClientCredentials| matches!(v, krafka::auth::ClientCredentials::Secret { .. });
    // KIP-794
    let _ = krafka::producer::ProducerBuilder::batch_size;
    // KIP-836
    { use krafka::admin::QuorumReplica as _; }
    // KIP-848
    let _ = |v: krafka::consumer::GroupProtocol| matches!(v, krafka::consumer::GroupProtocol::Consumer { .. });
    // KIP-848
    { use krafka::admin::ConsumerGroupDescription as _; }
    // KIP-853
    { use krafka::admin::QuorumNode as _; }
    // KIP-890
    { use krafka::producer::TransactionVersion as _; }
    // KIP-899
    { use krafka::MetadataRecoveryStrategy as _; }
    // KIP-899
    let _ = krafka::Kafka::rebootstrap;
    // KIP-899
    let _ = krafka::KafkaBuilder::metadata_recovery_strategy;
    // KIP-932
    { use krafka::share_consumer::ShareConsumer as _; }
    // KIP-932
    { use krafka::admin::SharePartitionOffset as _; }
    // KIP-939
    #[cfg(feature = "unstable-protocol")]
    let _ = krafka::producer::ProducerBuilder::two_phase_commit;
    // KIP-939
    #[cfg(feature = "unstable-protocol")]
    let _ = krafka::producer::TransactionalProducer::prepare;
    // KIP-939
    #[cfg(feature = "unstable-protocol")]
    let _ = krafka::producer::TransactionalProducer::complete;
    // KIP-939
    #[cfg(feature = "unstable-protocol")]
    { use krafka::producer::PreparedTxnState as _; }
    // KIP-966
    { use krafka::admin::PartitionDescription as _; }
    // KIP-994
    let _ = krafka::admin::ListTransactionsOptions::min_duration;
    // KIP-1005
    let _ = |v: krafka::admin::OffsetSpec| matches!(v, krafka::admin::OffsetSpec::LatestTiered { .. });
    // KIP-1023
    let _ = |v: krafka::admin::OffsetSpec| matches!(v, krafka::admin::OffsetSpec::EarliestPendingUpload { .. });
    // KIP-1030
    let _ = krafka::producer::ProducerBuilder::linger;
    // KIP-1043
    { use krafka::admin::GroupType as _; }
    // KIP-1043
    let _ = krafka::admin::ListConsumerGroupsOptions::types;
    // KIP-1066
    { use krafka::admin::LogDirDescription as _; }
    // KIP-1071
    { use krafka::admin::DescribedStreamsGroup as _; }
    // KIP-1071
    { use krafka::admin::DescribeStreamsGroupsOptions as _; }
    // KIP-1092
    let _ = |v: krafka::GroupMembershipOperation| matches!(v, krafka::GroupMembershipOperation::RemainInGroup { .. });
    // KIP-1092
    let _ = krafka::CloseOptions::group_membership_operation;
    // KIP-1102
    let _ = krafka::KafkaBuilder::metadata_recovery_rebootstrap_trigger;
    // KIP-1106
    let _ = |v: krafka::consumer::AutoOffsetReset| matches!(v, krafka::consumer::AutoOffsetReset::ByDuration { .. });
    // KIP-1123
    let _ = krafka::producer::ProducerBuilder::partitioner_rack_aware;
    // KIP-1142
    { use krafka::admin::ListedConfigResource as _; }
    // KIP-1142
    { use krafka::admin::ListConfigResourcesOptions as _; }
    // KIP-1152
    let _ = krafka::admin::ListTransactionsOptions::transactional_id_pattern;
    // KIP-1160
    let _ = krafka::admin::DescribeFeaturesOptions::node_id;
    // KIP-1206
    let _ = |v: krafka::share_consumer::AcquireMode| matches!(v, krafka::share_consumer::AcquireMode::RecordLimit { .. });
    // KIP-1206
    let _ = krafka::share_consumer::ShareConsumerBuilder::acquire_mode;
    // KIP-1222
    let _ = krafka::share_consumer::ShareConsumer::renew;
    // KIP-1222
    let _ = krafka::share_consumer::ShareConsumer::acquisition_lock_timeout;
    // KIP-1226
    { use krafka::admin::SharePartitionOffset as _; }
    // KIP-1258
    #[cfg(feature = "oauth-oidc")]
    { use krafka::auth::AssertionSource as _; }
    // KIP-1258
    #[cfg(feature = "oauth-oidc")]
    let _ = |v: krafka::auth::ClientCredentials| matches!(v, krafka::auth::ClientCredentials::Assertion { .. });
    // KIP-1274
    let _ = |v: krafka::consumer::GroupProtocol| matches!(v, krafka::consumer::GroupProtocol::Classic { .. });
    // KIP-1274
    let _ = |v: krafka::consumer::GroupProtocol| matches!(v, krafka::consumer::GroupProtocol::Consumer { .. });
    // KIP-1288
    let _ = krafka::Kafka::refresh_tls;
    // KIP-1288
    let _ = krafka::KafkaBuilder::tls_reload_interval;
}
